name: Publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    if: github.repository == 'uzser/shekel-streamer'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: uzser/shekel-streamer:latest
