name: Scheduled App Run

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Validate and mask sensitive data in JSON secret
        run: |
          if [ -z "${{ secrets.USERS_JSON }}" ]; then
            echo "::error::USERS_JSON secret is empty. Please provide a valid JSON."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Build and run Docker container
        run: |
          docker build -t shekel-streamer .
          docker run \
          -e "MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}" \
          -e "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
          -e 'USERS_JSON=${{ secrets.USERS_JSON }}' \
          -e "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
          shekel-streamer
